import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { mobileScene } from './svg/mobile.mjs';

const root = new URL('../', import.meta.url);
const themes = JSON.parse(await readFile(new URL('tools/svg/themes.json', root), 'utf8'));
const commonStyles = (await readFile(new URL('tools/svg/styles.css', root), 'utf8')).trim();
const check = process.argv.includes('--check');
const names = ['intro', 'workflow', 'aria-omr', 'ecms', 'hms'];
let stale = false;

// Generated SVGs embed their styles so they remain standalone GitHub images.
function render(source, palette) {
  const variables = Object.entries(palette).map(([name, value]) => `--${name}:${value}`).join(';');
  const style = `<style>\n    svg{${variables}}\n${commonStyles.split('\n').map(line => `    ${line.trim()}`).join('\n')}\n  </style>`;
  return source.replace('<!-- SHARED_STYLE -->', style)
    .replace('<svg ', '<!-- Generated by tools/build-svg.mjs. Edit tools/svg/ instead. -->\n<svg ');
}

await mkdir(new URL('assets/', root), { recursive: true });
for (const name of names) {
  const desktop = await readFile(new URL(`tools/svg/scenes/${name}.svg`, root), 'utf8');
  for (const [layout, source] of [['desktop', desktop], ['mobile', mobileScene(name, desktop)]]) {
    for (const [theme, palette] of Object.entries(themes)) {
      const filename = `${name}-${layout === 'mobile' ? 'mobile-' : ''}${theme}.svg`;
      const output = new URL(`assets/${filename}`, root);
      const svg = render(source, palette);
      if (check) {
        const existing = await readFile(output, 'utf8').catch(error => {
          if (error.code !== 'ENOENT') throw error;
          return null;
        });
        if (existing !== svg) {
          console.error(`Out of date: ${fileURLToPath(output)}`);
          stale = true;
        }
      } else {
        await writeFile(output, svg, 'utf8');
      }
    }
  }
}
if (stale) process.exitCode = 1;
else console.log(check ? 'All 20 SVG assets are up to date.' : 'Generated 20 SVG assets.');
